variables:
  NIX_CONFIG: "experimental-features = nix-command flakes"

default:
  image: nixos/nix:2.32.2

stages:
  - check

check:
  stage: check
  interruptible: true
  before_script:
    - nix profile install nixpkgs#cachix
    - cachix use unstoppablemango
  script:
    - nix flake check
